# General settings
title: here & there
title_img: "assets/images/theme/cloud.gif"
title_img_link: "/about"

plugins:
  - jekyll-paginate
  #- jekyll-responsive-image
  #- jekyll/tagging

# Other settings
code_css: "default"   # replace with highlight.js css style
paginate: 3
paginate_path: "/page/:num/"

# Tag settings
tag_page_dir:         tag
tag_page_layout:      tag_page

# Sass settings
sass:
  sass_dir: _sass

# Responsive image settings
responsive_image:
  # [Required]
  # Path to the image template.
  template: _includes/responsive-image.html
